/*global document*/
// This file is taken from GeoExt3
(function(doc, global){
    var specPath = 'test/spec/',
        dependencies = [
          'basics.test.js',
          'Application.test.js',
          'view/grid/LayerList.test.js',
          'view/grid/ApplicationList.test.js',
          'view/grid/UserList.test.js',
          'store/MoMo.admin.store.MapProjection.test.js',
          'store/MoMo.admin.store.Applications.test.js',
          'store/MoMo.admin.store.Language.test.js',
          'store/MoMo.admin.store.Layout.test.js',
          'store/MoMo.admin.store.NavigationTree.test.js',
          'store/MoMo.admin.store.ApplicationLayout.test.js',
          'store/MoMo.admin.store.AvailableModules.test.js',
          'store/MoMo.admin.store.Layers.test.js',
          'store/MoMo.admin.store.Users.test.js',
          'MoMo.admin.Application.test.js',
          'view/viewport/MoMo.admin.view.viewport.ViewportController.test.js',
          'view/viewport/MoMo.admin.view.viewport.ViewportModel.test.js',
          'view/tab/MoMo.admin.view.tab.CreateOrEditApplicationModel.test.js',
          'view/tab/MoMo.admin.view.tab.CreateOrEditApplicationController.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.LayerModel.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.LayoutModel.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.StartViewModel.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.LayoutController.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.LayerController.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.StartViewController.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.GeneralController.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.GeneralModel.test.js',
          'view/grid/MoMo.admin.view.grid.LayerListModel.test.js',
          'view/grid/MoMo.admin.view.grid.ApplicationListModel.test.js',
          'view/grid/MoMo.admin.view.grid.ApplicationListController.test.js',
          'view/grid/MoMo.admin.view.grid.UserListController.test.js',
          'view/grid/MoMo.admin.view.grid.UserListModel.test.js',
          'view/grid/MoMo.admin.view.grid.LayerListController.test.js',
          'model/MoMo.admin.model.Extent.test.js',
          'model/MoMo.admin.model.Layer.test.js',
          'model/MoMo.admin.model.User.test.js',
          'model/MoMo.admin.model.TileGrid.test.js',
          'model/MoMo.admin.model.LayerSource.test.js',
          'model/MoMo.admin.model.Application.test.js',
          'model/MoMo.admin.model.Base.test.js',
          'model/MoMo.admin.model.LayerAppearance.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.General.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.Layer.test.js',
          'view/panel/application/MoMo.admin.view.panel.application.Layout.test.js',
          'view/grid/MoMo.admin.view.grid.LayerList.test.js',
          'view/grid/MoMo.admin.view.grid.ApplicationList.test.js',
          'view/grid/MoMo.admin.view.grid.UserList.test.js',
          'view/container/MoMo.admin.view.container.MainContainer.test.js'
        ],
        getScriptTag = global.TestUtil.getExternalScriptTag,
        dependencyCnt = dependencies.length,
        i = 0;

    for(; i < dependencyCnt; i++) {
        doc.write(getScriptTag(specPath + dependencies[i]));
    }
}(document, this));
